### ISSUE TITLE
libpng16

### ISSUE THREAD

**Issue by 0xh3LL0** [Yggdrasill-Moe/Niflheim#1]
hello, i tried to build png2pgd and iar_pack but i end up with libpng error, i download libpng16 from the official site, but found no libpng16.lib there, after i search a bit i found it here: https://github.com/GlenDC/StarEngine-downloads/tree/master/Project/libs/Libpng_Release but it looks like this version is not compatible...
if you have it, may i use your libpng16?
or better yet if you have an already build of your tools, may i use it?

**Comment by Darkness-TX** [comment]
[lib&dll&include(VC).zip](https://github.com/Yggdrasill-Moe/Niflheim/files/2731088/lib.dll.include.VC.zip)

lib:
...\VC\lib
include:
...\VC\include
dll:
under the same directory as exe

**Comment by 0xh3LL0** [comment]
thank you very much!
