### ISSUE TITLE
png2pgd not working

### ISSUE THREAD

**Issue by imKota** [Yggdrasill-Moe/Niflheim#10]
png2pgd accept only pgd file, not png..

if i run `png2pgd BGM_BASE.PNG`

![image](https://user-images.githubusercontent.com/24241471/60390559-0f361600-9ae2-11e9-8019-291ad512b992.png)

if  i  run `png2pgd BGM_BASE.PGD`
result is BGM_BASE.PGDN

but what is .PGDN ?

**Comment by vnlovers** [comment]
Just rename .PGDN to .PGD. . I think the meaning of N in .PGDN is new

**Comment by imKota** [comment]
@vnlovers  thanks!
