### ISSUE TITLE
Failed to convert PNG to QNT, help

### ISSUE THREAD

**Issue by Aly2015** [Yggdrasill-Moe/Niflheim#11]
@Darkness-TX 
![image](https://user-images.githubusercontent.com/40235516/70952124-5029e300-20a0-11ea-916f-30cf556a7019.png)

**Comment by Darkness-TX** [comment]
Put *.qnt and *.qnt.png in a folder
This program must run with the original qnt
png2qnt.exe folder
then a new qnt(name is *.qnt.new) will be generated

**Comment by Aly2015** [comment]
还是不行
AliceSoft工具除了ALD_unpack之外，都不能正常运作，能给我一份打包好的吗？
我怀疑是我的编译环境有问题，但用vs生成时又没有报错只有几个警告……
程序小白，一切操作都是百度来的……

**Comment by Darkness-TX** [comment]
你怕是没有libpng16.dll？
编译没报错就没问题，你不如上传文件吧

**Comment by Aly2015** [comment]
解决了运行问题，就是编译环境的问题
用win32平台编译后，运行程序就可以看到有输出了，图片分辨率对了，但内容却是错误的，所有图片经过QNT2PNG解码后都变成了条纹
![image](https://user-images.githubusercontent.com/40235516/70959488-6e4f0d80-20b7-11ea-8847-1341b66e3d67.png)
从
![image](https://user-images.githubusercontent.com/40235516/70959812-22e92f00-20b8-11ea-9320-79dabb929987.png)
变成了
![image](https://user-images.githubusercontent.com/40235516/70959835-34cad200-20b8-11ea-9773-a70b0c04b788.png)
文件是
[CG0049.QNT](https://github.com/Aly2015/qnt/blob/master/CG0049.QNT)

**Comment by Aly2015** [comment]
PNG2QNT也是有输出了，但结果不正确，比原来的文件小得多
![image](https://user-images.githubusercontent.com/40235516/70961878-27184b00-20be-11ea-8bfa-13f07fe6e288.png)

**Comment by Aly2015** [comment]
@Darkness-TX 
可能是libpng库的问题？
libpng默认是win32平台的，但AliceSoft无法加载32位库无法生成，我把libpng改成用x64来生成，此时AliceSoft就可以生成了，但使用libpng库的程序只是显示默认文字就什么都不处理了，
我把AliceSoft和libpng库都改成用win32生成，结果就像上面那样了……

**Comment by Darkness-TX** [comment]
这周事情很多，我下周再来看看这问题，应该不是什么大问题，看图片估计是长宽的问题

**Comment by Aly2015** [comment]
搞定了，问题是我没有添加zlib库……
我之前只添加了libpng和zlib的头文件以及libpng的库……
没有readme的编译指导，程序小白只能先编译再按错误提示百度……

**Comment by rentommy** [comment]
我没接触过这个语言，能教我一下怎么安装libpng吗
