### ISSUE TITLE
Can't build ExHIBIT tool

### ISSUE THREAD

**Issue by DSHinako21** [Yggdrasill-Moe/Niflheim#12]
i have error when build this tool, plz help and thanks first

1>------ Build started: Project: gyu2png, Configuration: Debug x64 ------
2>------ Build started: Project: png2gyu, Configuration: Debug x64 ------
1>gyu2png.c
2>png2gyu.c
1>C:\Users\huy10\Downloads\Compressed\Niflheim-master\Niflheim-master\ExHIBIT\gyu2png\gyu2png.c(1,1): warning C4819:  The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss
2>C:\Users\huy10\Downloads\Compressed\Niflheim-master\Niflheim-master\ExHIBIT\png2gyu\png2gyu.c(1,1): warning C4819:  The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss
1>C:\Users\huy10\Downloads\Compressed\Niflheim-master\Niflheim-master\ExHIBIT\gyu2png\gyu2png.c(14,10): error C1083:  Cannot open include file: 'png.h': No such file or directory
2>C:\Users\huy10\Downloads\Compressed\Niflheim-master\Niflheim-master\ExHIBIT\png2gyu\png2gyu.c(14,10): error C1083:  Cannot open include file: 'png.h': No such file or directory
2>Done building project "png2gyu.vcxproj" -- FAILED.
1>Done building project "gyu2png.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by Darkness-TX** [comment]
https://github.com/Yggdrasill-Moe/Niflheim/issues/1

**Comment by anhhuyninja1234** [comment]
Thanks for your reply, but after i drop lib and include to VC
the other error has appear

1>------ Build started: Project: gyu2png, Configuration: Debug x64 ------
2>------ Build started: Project: png2gyu, Configuration: Debug x64 ------
1>gyu2png.obj : error LNK2019: unresolved external symbol png_create_write_struct referenced in function WritePng
1>gyu2png.obj : error LNK2019: unresolved external symbol png_create_info_struct referenced in function WritePng
1>gyu2png.obj : error LNK2019: unresolved external symbol png_write_info referenced in function WritePng
1>gyu2png.obj : error LNK2019: unresolved external symbol png_write_row referenced in function WritePng
1>gyu2png.obj : error LNK2019: unresolved external symbol png_write_end referenced in function WritePng
1>gyu2png.obj : error LNK2019: unresolved external symbol png_destroy_write_struct referenced in function WritePng
1>gyu2png.obj : error LNK2019: unresolved external symbol png_init_io referenced in function WritePng
1>gyu2png.obj : error LNK2019: unresolved external symbol png_set_IHDR referenced in function WritePng
1>C:\Users\huy10\Downloads\Compressed\Niflheim-master\Niflheim-master\ExHIBIT\x64\Debug\gyu2png.exe : fatal error LNK1120: 8 unresolved externals
1>Done building project "gyu2png.vcxproj" -- FAILED.
2>png2gyu.obj : error LNK2019: unresolved external symbol png_create_read_struct referenced in function ReadPng
2>png2gyu.obj : error LNK2019: unresolved external symbol png_create_info_struct referenced in function ReadPng
2>png2gyu.obj : error LNK2019: unresolved external symbol png_read_info referenced in function ReadPng
2>png2gyu.obj : error LNK2019: unresolved external symbol png_read_image referenced in function ReadPng
2>png2gyu.obj : error LNK2019: unresolved external symbol png_read_end referenced in function ReadPng
2>png2gyu.obj : error LNK2019: unresolved external symbol png_destroy_read_struct referenced in function ReadPng
2>png2gyu.obj : error LNK2019: unresolved external symbol png_init_io referenced in function ReadPng
2>png2gyu.obj : error LNK2019: unresolved external symbol png_get_rowbytes referenced in function ReadPng
2>png2gyu.obj : error LNK2019: unresolved external symbol png_get_IHDR referenced in function ReadPng
2>C:\Users\huy10\Downloads\Compressed\Niflheim-master\Niflheim-master\ExHIBIT\x64\Debug\png2gyu.exe : fatal error LNK1120: 9 unresolved externals
2>Done building project "png2gyu.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

I drop file you give in #1  like this link
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\lib
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\include

Can't find the VC\lib and the VC\include like you said in #1

**Comment by Darkness-TX** [comment]
Because I use VS2015.It seems that you don't know much about VS settings.
First change Debug X64 to Release X86.Then change project property.
![QQ截图20200312210217](https://user-images.githubusercontent.com/22828117/76524679-6d0a6280-64a5-11ea-9f0e-b6b883fb0959.png)
![QQ截图20200312210217](https://user-images.githubusercontent.com/22828117/76524695-7398da00-64a5-11ea-90e2-b7a92d9ce1b2.png)
See this:https://en.wikibooks.org/wiki/C%2B%2B_Programming/Compiler/Linker/Libraries/Configuring_Visual_Studio#Library_files

**Comment by Darkness-TX** [comment]
Of course, there is a more convenient way. You can upload the gyu files to me, because I can't guarantee that the program is applicable to all gyu files.

**Comment by anhhuyninja1234** [comment]
Sr because i don't explain clearly for my issue. All i need is how to decode and encode rld file(because this tool can edit the decode file rld https://github.com/regomne/lneditor)
or export to txt and import them to rld after edited.
Here is the rld file from imouto paradise 3
[rld IM3.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/4325577/rld.IM3.zip)

**Comment by Darkness-TX** [comment]
1.Decrypt rld
python rld_dec.py
2.dump text
python rld_text_output.py
[rld_done.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/4327744/rld_done.zip)

**Comment by Darkness-TX** [comment]
![QQ截图20200313113159](https://user-images.githubusercontent.com/22828117/76587750-e5ae0500-651f-11ea-8b3e-df4e537b8fe6.png)
why there is Chinese?
where are you come from?

**Comment by anhhuyninja1234** [comment]
This is a test to check the game can recognize other character (I use this tool before go here
https://github.com/marcussacana/RLDManager, but this tool can't detect all text)
And I'm from Vietnam
Anyway, how to import them after i edit (translate) .txt file ? Can you point out for me?
First time, i think i can use the file has been decode to edit with the tool i recommend before but it's not working and i don't know why ( This is the tool[Ineditor_2_1_2.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/4328234/Ineditor_2_1_2.zip) )

And i can't dump text rld file in IM 3 eng ver. (I need to compare between eng and jp ver)
This is the file from eng ver (they use ANSI not cp932) [rld IM 3 Eng ver.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/4328220/rld.IM.3.Eng.ver.zip)

**Comment by Darkness-TX** [comment]
Different game decryption keys are different, so you can't edit them, unless you know what the key of this game is, ineditor I haven't used it, I only wrote the dump program, and the import program didn't have the chance to write it

**Comment by anhhuyninja1234** [comment]
So u mean there is no chance to translate this game, right?

**Comment by Darkness-TX** [comment]
All programs of the ExHIBIT project are based on 夏の色のノスタルジア.
Then the Chinese translation‘s leader disappeared, so I didn't continue to improve ExHIBIT project.

**Comment by Darkness-TX** [comment]
Of course, I didn't have much time to deal with it, so I shelved this project

**Comment by anhhuyninja1234** [comment]
So sad to hear that, my friend really excited to translate this game and more excited when i said your tool can dump text. But now you say that, i think i will shelve this PJ. Anyway thanks for your all help bro.

**Comment by Darkness-TX** [comment]
Maybe one day when I have time, I will improve this perfect, just like another issue which is opened.

**Comment by anhhuyninja1234** [comment]
Oh that's nice to hear that 👌 I will reopen and wait you

**Comment by Darkness-TX** [comment]
As a crucial question,which language do you want to edit (translate),and it's codepage is?
shift-jis to ??? or english to ???

**Comment by anhhuyninja1234** [comment]
I'm from Vietnam so of course it's Vietnamese bro, codepage is utf 8. But don't worry about problem of codepage, i can change font original to my font mod. And that is why you can see Chinese in first file because this is my test. Anyway all i need is hope you can make the import and export file to translate.
