### ISSUE TITLE
.cpz repack (CMVS)

### ISSUE THREAD

**Issue by imKota** [Yggdrasill-Moe/Niflheim#13]
Hello!

Please can you add support repack ***.cpz** for games [Aoi Tori](https://vndb.org/v21523) and [Amatsutsumi](https://vndb.org/v18852)

**Comment by Darkness-TX** [comment]
No repack program,it‘s too much complex to unpack and repack *.cpz.
I use hook about repack probrem.


But.......AoiTori(青鸟)?
I am the programmer of Chinese unofficial translation's  AoiTori.
So,the programs in this repo(Niflheim/cmvs) were used for AoiTori.
![QQ截图20200325143036](https://user-images.githubusercontent.com/22828117/77509290-6e755b00-6ea7-11ea-9c68-0084f73e4aaa.png)
![QQ截图20200325143145](https://user-images.githubusercontent.com/22828117/77509354-84831b80-6ea7-11ea-8fb5-7c71b33430ba.png)

**Comment by imKota** [comment]
@Darkness-TX 
> So,the programs in this repo(Niflheim/cmvs) were used for AoiTori.

Now we are planning to translate Amatsutsumi ))

**Comment by imKota** [comment]
@Darkness-TX 
>I use hook about repack probrem.

Hmm.. Is it suitable for Amatsutsumi?

**Comment by Darkness-TX** [comment]
I don't know,didn't test,maybe.

**Comment by imKota** [comment]
> I don't know,didn't test,maybe.

Hmm
can you share on my mail aleksey-nyaka@yandex.ru ?

**Comment by Darkness-TX** [comment]
There are many programs. You can translate the text at the beginning of the game to me. Let me try.
For different games, the hook's configuration should also be changed.

**Comment by imKota** [comment]
> There are many programs. You can translate the text at the beginning of the game to me. Let me try.
> For different games, the hook's configuration should also be changed.

10 min, ok?

**Comment by Darkness-TX** [comment]
ummmm,do you know how to unpack cpz and dump text from ps3?

**Comment by imKota** [comment]
> ummmm,do you know how to unpack cpz and dump text from ps3?

Yeah))

CPZV6Unpacker for unpack cpz
Ps2TextDumper for dump *.ps3 to text
PurplePS3Packer for repack text to *.ps3

**Comment by Darkness-TX** [comment]
ok

**Comment by imKota** [comment]
@Darkness-TX done
We translated the first 20 lines into Russian. In folder **2.ps3_done**

[script.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/4379718/script.zip)

**Comment by Darkness-TX** [comment]
Which code page is Russian?Not Unicode.And which font is the default font in Russian system?

**Comment by imKota** [comment]
> Which code page is Russian?Not Unicode.And which font is the default font in Russian system?

I use in hooks

```
	lplf->lfCharSet = RUSSIAN_CHARSET;
	wcscpy(lplf->lfFaceName, L"Minion Pro");
```

**Comment by Darkness-TX** [comment]
This is for CreateFont.What about MultiByteToWideChar?
https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar
https://docs.microsoft.com/zh-cn/windows/win32/intl/code-page-identifiers

**Comment by imKota** [comment]
> What about MultiByteToWideChar?

Yes, I used it.

**Comment by Darkness-TX** [comment]
WHAT??
CodePage = 932; ????
This is the codepage of Janpanese.
If you use 932,the Russian translation must import with 932.......
then lplf->lfCharSet can't use RUSSIAN_CHARSET,it must SHIFTJIS_CHARSET.....
But codepage 932 has all Russian letters.There will be no problem with the display

First,update game to version 1.03.You can run GameUpdate32.exe.
Unpack file into the game root directory.
Then run Longinus_Start.exe.
Only for test.
![QQ截图20200325202535](https://user-images.githubusercontent.com/22828117/77536841-fecb9400-6ed7-11ea-9834-87f83c6fda8b.png)

[test.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/4380864/test.zip)

**Comment by imKota** [comment]
> CodePage = 932; ????
> This is the codepage of Janpanese.
> If you use 932,the Russian translation must import with 932.......

Yeah xDD

**Comment by imKota** [comment]
> First,update game to version 1.03.You can run GameUpdate32.exe.
> Unpack file into the game root directory.
> Then run Longinus_Start.exe.
> Only for test.

Everything works. but I have a question. Can I somehow get rid of the spaces between the letters?

![image](https://user-images.githubusercontent.com/24241471/77537838-cdd76900-6eaf-11ea-883d-0a3685914287.png)

**Comment by imKota** [comment]
And wordwrap not working?

Since the words break off in the middle.

not correct
```
Раскалённая настолько, чт
о если разбить яйцо и выли
ть его на землю, оно тут же
 поджарится.
```
correct
```
Раскалённая настолько, что 
если разбить яйцо и вылить 
его на землю, оно тут же
поджарится.

```

![image](https://user-images.githubusercontent.com/24241471/77538280-89000200-6eb0-11ea-9d14-fc517a94759d.png)

**Comment by Darkness-TX** [comment]
I don't know where to change the word spacing.So the word spacing is locked.
It looks like the number of characters per line is fixed.
CJK uses characters to express meaning, other languages use words to express meaning.
So I think there's no way make wordwrap working unless  official company improve it.

**Comment by imKota** [comment]
Hmm.
Can you send me source for Longinus.dll ?

**Comment by Darkness-TX** [comment]
Yggdrasill-Moe/Longinus

**Comment by imKota** [comment]
What change about encoding and default font?

**Comment by Darkness-TX** [comment]
No change.If you want to use 932.

**Comment by imKota** [comment]
> No any change.If you want to use 932.

But if i want change encoding and font?

**Comment by imKota** [comment]
https://github.com/Yggdrasill-Moe/Longinus/blob/fabf10381b80a61539ae2209ff7ae3dd822f0420/Longinus/Longinus/Longinus.c#L146

https://github.com/Yggdrasill-Moe/Longinus/blob/fabf10381b80a61539ae2209ff7ae3dd822f0420/Longinus/Longinus/Longinus.c#L151

https://github.com/Yggdrasill-Moe/Longinus/blob/fabf10381b80a61539ae2209ff7ae3dd822f0420/Longinus/Longinus/Longinus.c#L155

**Comment by Darkness-TX** [comment]
This is only used to display symbols that are not in Chinese codepage.

**Comment by Darkness-TX** [comment]
> No any change.If you want to use 932.
> 
> But if i want change encoding and font?

CharSet in Longinus.ini

**Comment by Darkness-TX** [comment]
[ChangeFace]
ChangeFace_Mode=ALL
Face=XXX

**Comment by MZSHproject** [comment]
> > First,update game to version 1.03.You can run GameUpdate32.exe.
> > Unpack file into the game root directory.
> > Then run Longinus_Start.exe.
> > Only for test.
> 
> Everything works. but I have a question. Can I somehow get rid of the spaces between the letters?
> 
> ![image](https://user-images.githubusercontent.com/24241471/77537838-cdd76900-6eaf-11ea-883d-0a3685914287.png)

It's full-width character.
russian character are all over 0x80, CMVS shwo these use two bytes.

**Comment by MZSHproject** [comment]
> > First,update game to version 1.03.You can run GameUpdate32.exe.
> > Unpack file into the game root directory.
> > Then run Longinus_Start.exe.
> > Only for test.
> 
> Everything works. but I have a question. Can I somehow get rid of the spaces between the letters?
> 
> ![image](https://user-images.githubusercontent.com/24241471/77537838-cdd76900-6eaf-11ea-883d-0a3685914287.png)

A way to show them. you can map the chars. It's easy. Just like YU-RIS engine I told you.

**Comment by imKota** [comment]
> It's full-width character.
> russian character are all over 0x80, CMVS shwo these use two bytes.

That is, it does not fix it?
