### ISSUE TITLE
自己解包游戏时遇到一些问题想请教

### ISSUE THREAD

**Issue by Chen-Yufeng** [Yggdrasill-Moe/Niflheim#14]
项目的维护者你好，由于网上交流这块的地方基本找不到，想请教一下，希望能得到指点，谢谢！
我正在解的一个游戏资源文件后缀为游戏名+.vpk, .arc, .scb, .bmx。经过搜索，有少量的线索指向叫做ARCG的引擎，这些资源文件的开头解析到ASCII也是“ARCG”。文件结构较为简单，没有压缩和加密，所以解起来挺容易，封包程序我也实现了。但是解包CG的时候发现一部分JPG格式还有一部分文件格式未知，如下图所示。
![image](https://user-images.githubusercontent.com/32028085/89911139-ab0ddd00-dc23-11ea-8022-229618eaaedc.png)
[設定画面.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/5057631/default.zip)

我研究了很久也没有进展，只能确定这个文件是图片。

最后，我想请问一下可以通过一些社交工具（QQ之类）的联系吗，我初入汉化不久，有编程基础能看得懂基本的汇编和基本的调试手段，有时碰到难懂的疑难问题但是找不到人请教，能研究的我会自己查找资料，不得门路的时候希望能得到大佬的指点，谢谢了。

**Comment by Chen-Yufeng** [comment]
我的邮箱是0xtomriddle@gmail.com，如果联系方式不便于直接告知，可以发到我的邮箱，再次感谢！

**Comment by Darkness-TX** [comment]
纯逆向方面我可能帮不了你，讲真我其实也只是个抄代码的。
而你上传的这个文件，如果真是图片那看起来不是简单的rgb位图数据，不是压缩了就是加密了。

还有vpk......不会是psv的吧

**Comment by Chen-Yufeng** [comment]
是PC游戏，如果是压缩了应该如何用OD找到解压那一块的代码呢，有什么技巧吗？我主要是想学习汉化，顺便学习逆向，大佬方便给个联系方式吗，QQ/TG之类的都行，感觉issue交流不是很方便QAQ

**Comment by Darkness-TX** [comment]
找了下，还真是压缩，因为看文件大小就觉得不寻常，而且数据也不太像加密过那种杂乱，果真是压缩了。
https://github.com/morkt/GARbro/tree/e384ec2ef7542fa3e8a5489a98b5ea127cd7e1a2/ArcFormats/Tanaka

没经验........逆向真不熟，我只是个代码的搬运工。
N年前到现在不少人都找过我跟我说过想学汉化，男的女的汉化组的非汉化组的都有，当然最终他们都放弃了，终究三分钟热度，只有少数一个手数得过来的人靠自学成才，所以你如果真有心那应该没啥是困难的，无非都是从抄代码开始，抄多了就懂了，至于逆向这个，还是系统去学习好，网上大把课程，像我就没学过逆向，极少情况需要开调试器。

联系方式？我联系方式挺好找的吧，前阵子还有个啥都不懂的妹子加过来问问题，倒不如说能找到这仓库的应该都认识我，现在都是随缘给QQ的了

**Comment by Chen-Yufeng** [comment]
谢谢！我去看看那个项目的解压代码。emm我是搜索DDSystem找到这个仓库的，去搜了下，发现您同名的贴吧和微博，没能找到QQ，大佬方便给个吗？

**Comment by Chen-Yufeng** [comment]
大佬的QQ刚刚已经找到了~希望能通过一下
