### ISSUE TITLE
Can't build cmvs ps3 encoder

### ISSUE THREAD

**Issue by GreenNBlacko** [Yggdrasill-Moe/Niflheim#15]
![image](https://user-images.githubusercontent.com/45263750/90337798-8764e100-dfed-11ea-832c-b370ccb268da.png)
![image](https://user-images.githubusercontent.com/45263750/90337843-d4e14e00-dfed-11ea-97ef-92ccaff83613.png)

**Comment by Darkness-TX** [comment]
[ps3_encoder.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/5088819/ps3_encoder.zip)
ps3_encoder.exe folder

**Comment by GreenNBlacko** [comment]
what's the usage? should I provide a txt file with the translated ps3 or the original ps3, keeping the txt in the same folder?

**Comment by Darkness-TX** [comment]
Only used to encrypt files decrypted by ps3_decoder,no have translation related programs.
Cmvs wants to achieve translation is not simple,there is no universal program.
