### ISSUE TITLE
SOFTPAL_ADV_SYSTEM

### ISSUE THREAD

**Issue by hacker123-321** [Yggdrasill-Moe/Niflheim#16]
after i used microsoft visual novel creater file fuckpac.exe 
i used fuckpac to extract to the  data.pac file to the data folder in game folder but file game.exe not run
after i delete data folder then game.exe run again
if i ceater new data.pac file with fuckpac, game.exe has error

**Comment by Darkness-TX** [comment]
If the game want to read abc.PGD in data.pac,steps of SOFTPAL_ADV_SYSTEM‘s patch reading:
abc.PGD in a foler which name is data,no find? ->abc.PGD in a pac which name is data.pac.
So if you used fuckpac to extract to the data.pac file to the data folder in game folder,the game will read file which in data folder before data.pac.
The game.exe not run because fuckpac will decrypt text.dat in data.pac when (data[0] == 0x24)//$,and the game.exe can't read text.dat in decrypted,you can fuckpac -en text.dat to recover text.dat to encrypted.
Pac in different game have a slight difference,if you repack pac the game doesn't work,you'd better use patch.
That is put your new alter file in a folder which name is the same as you extract it in which pac.

**Comment by hacker123-321** [comment]
i can not build fuckfont it have error
[fuckfont.log](https://github.com/Yggdrasill-Moe/Niflheim/files/5192604/fuckfont.log)

**Comment by Darkness-TX** [comment]
use vs,add freetype2

**Comment by hacker123-321** [comment]
and i try encrypted text.dat in data folder but game not run 
vs and freetype 2, where this?

**Comment by hacker123-321** [comment]
i download lib.dll.include.VC and follow the instructions but have error as fuckfontlog.txt

**Comment by Darkness-TX** [comment]
What do you want to do? fuckfont is usually not needed.
Based on your needs, I'll think what you should do.

**Comment by hacker123-321** [comment]
i want to game shin-neko ～再会した妹との新たな関係～ to vietnamese

**Comment by hacker123-321** [comment]
but game can not read char vietnamese it will become "?"

**Comment by Darkness-TX** [comment]
Can Vietnamese char all be found in MAJOKOI_SJIS.txt？
If not,it will become "?".
I know how to do it,it must change CreateFont-> iCharSet to VIETNAMESE_CHARSET.
I'll download the game at night to test it.
which is the default font of Vietnamese in Windows？Arial？

**Comment by hacker123-321** [comment]
thank you i try agian

**Comment by hacker123-321** [comment]
sorry but MAJOKOI_SJIS.txt lack of many Vietnamese char

**Comment by Darkness-TX** [comment]
I see your other issues,you can try these change:
open SRL.ini,change FontCharset=0x80 to FontCharset=0xA3,FaceName= to FaceName=Arial

**Comment by hacker123-321** [comment]
SRL.ini where?

**Comment by Darkness-TX** [comment]
https://github.com/marcussacana/StringReloads/issues/5
this project

**Comment by hacker123-321** [comment]
i try it, chars has space very good

**Comment by Darkness-TX** [comment]
OK?
![QQ截图20200909230750](https://user-images.githubusercontent.com/22828117/92617144-90e22000-f2f1-11ea-8e4f-d1025b37ff4a.png)
![QQ截图20200909230622](https://user-images.githubusercontent.com/22828117/92617082-86c02180-f2f1-11ea-8a2c-0d9334fc7ee9.png)
![QQ截图20200909230706](https://user-images.githubusercontent.com/22828117/92617113-8c1d6c00-f2f1-11ea-9ac9-f0b755f08d9b.png)

**Comment by hacker123-321** [comment]
What is your method?

**Comment by hacker123-321** [comment]
if you use StringReloads, it has not  char vietnamese
example: ố ồ ộ ổ ỗ

**Comment by Darkness-TX** [comment]
only for test the first text in this game.
[SHIN_NEKO_VN.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/5196526/SHIN_NEKO_VN.zip)

**Comment by hacker123-321** [comment]
please i need guide your method

**Comment by Darkness-TX** [comment]
Can you run this program?
If it works, I'll think about how to deal with it more easily.
And I want to know what letters are in Vietnamese

**Comment by hacker123-321** [comment]
I can run your program
But it run one text and finish program 
Char vietnamese : ă â ê ô ơ ư ằ ắ ẳ ẵ ặ ầ ẩ ậ ẫ ấ ề ể ệ ế ễ ồ ố ổ ộ ỗ ờ ớ ở ợ ỡ ừ ử ự ữ ứ

**Comment by Darkness-TX** [comment]
Now Vietnamese in Windows is cp1258？

**Comment by hacker123-321** [comment]
sorry because Now I can answer you i  am very busy
yeah and then

**Comment by hacker123-321** [comment]
Please answer me
I don't know what to do next

**Comment by Darkness-TX** [comment]
Sorry,I have other things must be finished at this weekend. I'll tell you next week.
QAQ

**Comment by hacker123-321** [comment]
Yeah thank you

**Comment by Darkness-TX** [comment]
[VN.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/5223231/VN.zip)
