### ISSUE TITLE
所有的tbl文件都是针对游戏本身单独设计的吗

### ISSUE THREAD

**Issue by QYF** [Yggdrasill-Moe/Niflheim#17]
请问starless这个游戏的码表还留有吗（majiro引擎）？码表设计的时候都需要考虑些什么呢

**Comment by Darkness-TX** [comment]
文本翻译完，然后统计出现的汉字数，然后制作个伪shift-jis码表，我一般选择在0x889F开始插入汉字，简单来说其实就是映射表而已。
[STARLESS.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/5318318/STARLESS.zip)

**Comment by QYF** [comment]
我是之前接手starless的程序员，打包的问题没搞定所以我直接跑路了。后来他们说找了大佬你把问题解决了我就来学习一下。另外翻译他想校对出2.0的补丁，但找不到你，他又把你之前给他的py文件删了，所以来烦了我一阵
