### ISSUE TITLE
some tools didnt work

### ISSUE THREAD

**Issue by 0xh3LL0** [Yggdrasill-Moe/Niflheim#2]
my build environment: win8.1, msbuild 2017, win8.1 sdk installed
all builds are release win32

0 warning, 0 error during compilation
![ddperror](https://user-images.githubusercontent.com/23132217/50745603-ba65c100-125d-11e9-9c25-efee860b4f1b.jpg)

0 warning, 0 error during compilation
![ddp3](https://user-images.githubusercontent.com/23132217/50745606-bf2a7500-125d-11e9-9e81-f898df85c571.jpg)

0 warning, 0 error during compilation
![gyuerror](https://user-images.githubusercontent.com/23132217/50745612-c487bf80-125d-11e9-9e5e-a65424c13d7f.jpg)

0 warning, 0 error during compilation
![iarerror](https://user-images.githubusercontent.com/23132217/50745670-17fa0d80-125e-11e9-947f-9aa49b5b70f7.jpg)

0 warning, 0 error during compilation
![iarerror2](https://user-images.githubusercontent.com/23132217/50745675-1d575800-125e-11e9-95e7-4fdd90270053.jpg)

2 warning, 0 error during compilation
![pac](https://user-images.githubusercontent.com/23132217/50745680-1fb9b200-125e-11e9-8b46-7f7a0907ca04.jpg)
![pac2](https://user-images.githubusercontent.com/23132217/50745686-26482980-125e-11e9-9bce-97602c142fcc.jpg)

0 warning, 0 error during compilation
![ps3de](https://user-images.githubusercontent.com/23132217/50745689-29431a00-125e-11e9-8dd5-c9910a1b8a18.jpg)

8 warning, 0 error during compilation
![ps3enc](https://user-images.githubusercontent.com/23132217/50745692-2d6f3780-125e-11e9-9def-2d231fe70d46.jpg)
![ps3en](https://user-images.githubusercontent.com/23132217/50745695-306a2800-125e-11e9-99b9-4b90c4703740.jpg)

0 warning, 0 error during compilation
![sec5](https://user-images.githubusercontent.com/23132217/50745698-32cc8200-125e-11e9-997f-23fb5dba938b.jpg)

0 warning, 0 error during compilation
![sec52](https://user-images.githubusercontent.com/23132217/50745701-352edc00-125e-11e9-928f-ca66f90ab897.jpg)

**Comment by Darkness-TX** [comment]
Ummmm..........
The instructions are written in Chinese, and there is no time to write English.
If you can understand some simple code you should know how to use it.
Most of the methods of use are
xxx.exe originalfile
or
xxx.exe folder
It used to be a personal tool. Even the Chinese instructions didn't make up for it, not to mention English. So if you have any usage questions, just ask. :)

**Comment by 0xh3LL0** [comment]
i guess you're right... i need to give them file to work
but since i dont have many games, i only test 3 of them

cmvs
it still give me error, but i guess its because the tool is not compatible
![error3](https://user-images.githubusercontent.com/23132217/50804323-04af7680-1320-11e9-8e44-2b1ff6ac1fc2.png)
i cant test ps3 encoder yet since the ps3 decoder didnt work

softpal
fuckpac, fuckfont, and png<->pgd works
but the pac text didnt work
![error4](https://user-images.githubusercontent.com/23132217/50804403-5821c480-1320-11e9-86e5-dca842a0a506.png)
the thing is, i tried to remove the chinese letter, and viola! it works... and stop at certain point
![error5](https://user-images.githubusercontent.com/23132217/50804429-7982b080-1320-11e9-8e75-9fbcee2c0ff0.png)

studio seldom adventure system
all works

here is the game files in case you want to inspect it, and i hope you can fix it soon.
[gamefiles.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/2734887/gamefiles.zip)

thank you in advance.

**Comment by Darkness-TX** [comment]
SOFTPAL_ADV_SYSTEM
Script.src records the offset of all text in text.dat, so if you want to change the length of the text, you must record the location of the offset in script.src and change it after import. script.txt is Record offset address
pac_text.py need to find the first number that you will change the length of the text.
in this text.dat,i think is 00000006,so 00000006's offset in text.dat is 0xa0
![_20190108101005](https://user-images.githubusercontent.com/22828117/50805491-98d40a80-132d-11e9-8ffa-14b8e1819871.png)
then change line 43 in pac_text.py to
if i >= 0x06:
change line 76 in pac_text.py to
if int(row[0]) >= 0x06:

goto script.src,find the offset that appears in 0xa0.From experience, the smaller the text number, the more offset addresses are searched. You can search for the offset of the subsequent text number. Then the smaller number is naturally in front of this offset, and then judge which one is Really record the text offset address.

example:
○00000011○セーブメニュー in text.dat is 0xeb
eb 00 00 00 first appeared in script.src is 0x32988
○00000009○システムメニュー in text.dat is 0xc1
c1 00 00 00 first appeared in script.src is 0xde4,ummmmm........but second appeared in script.src is 0x328d8
let me see ○00000010○ウィンドウの消去,in text.dat is 0xd6
d6 00 00 00 first appeared in script.src is 0x2db1c,but second appeared in scripte.src is 0x32930.
ok,i think number 9 in script.src is 0x328d8,number 10 in script.src is 0x32930
Combined with the above judgment,i think number 6 in script.src is 0x327d0

Now,change line 38 in pac_text.py to
ofp.seek(0x327d0)

Finish.
![_20190108105435](https://user-images.githubusercontent.com/22828117/50806960-d2a80f80-1333-11e9-97dd-e9d60e9f9ab7.png)

The opcode of script.src is not well analyzed. Different games may be different.This is a good general method that Destinyの火狐 thinks of.Just need some judgment and luck.

**Comment by Darkness-TX** [comment]
The cmvs engine is updated very diligently. Is script.cpz CPZ7 or CPZ6 or something else?
The cmvs engine's key is different for each game, and the tools I wrote are based on the アオイトリ.
There is no general way to do not need inline hooks,
I am not sure the ps3 files you gave can dump the text with no error

**Comment by 0xh3LL0** [comment]
okay, so i did a test, i change pac_text.py as your instruction,
there is no problem with text dumping,
but when i tried to pack them, there is an issue, and i didnt even edit the text yet...

**Comment by Darkness-TX** [comment]
Because you modified the code........................

if int(row[0]) >= 0x06:
	ofp.seek(dict[str(int(row[0]))])
	ofp.write(int2byte(dst.tell()))
	line = row[1].encode('932')

if int(row[0]) >= 0x06:
	ofp.seek(dict[str(int(row[0]))])
	ofp.write(int2byte(dst.tell()))
	line = row[1].encode('932')
else:
	line = row[1].encode('932')

**Comment by 0xh3LL0** [comment]
yay, it works now...
but seriously, as i said earlier, it wont run unless i remove the chinese letter, so i thought that line with chinese codepage were not necesary either,
sorry for the trouble...
![working](https://user-images.githubusercontent.com/23132217/50872092-b4541980-13f0-11e9-8d35-9d665ae404da.png)
anyway, another thing from me, as you can see, the text is cutted, so i assume softpal dont support wordwrap, is there is a way to do force linebreaks?
i tried "\n" but it didnt works...

**Comment by Darkness-TX** [comment]
<br>

**Comment by 0xh3LL0** [comment]
nice...
![working2](https://user-images.githubusercontent.com/23132217/50940981-addba580-14b5-11e9-854e-f990f0128ac5.png)

you dont know how glad i know you, once again, thank you very much!

**Comment by Veshurik** [comment]
Hello, I noticed some of you have translation for Koikake. 

I have only that script and translate it step by step. Am I doing all right?
[koikake jp.txt](https://github.com/Yggdrasill-Moe/Niflheim/files/3125389/koikake.jp.txt)
