### ISSUE TITLE
Rioshiina Update / specific game request

### ISSUE THREAD

**Issue by Presi5** [Yggdrasill-Moe/Niflheim#20]
Firts of all, I really appreciate your work. The tools you made for the game Bloody Rondo work perfectly. Now I'll go for the main topic: I'm an admin of a translation team, and, if possible, I'd like you to make an update of those tools regarding the game Sorcery Joker [https://vndb.org/v16337](url), because Bloody Rondo tools are specific for Bloody Rondo, obviously. We don't know any way to update the tools for ourselves. As you may wondered, this is meant for a translation project.

Thank you and keep working hard.

**Comment by Darkness-TX** [comment]
Sorry to see this issue late because I am working on other translation projects recently.
I will try to update the code for this game as soon as possible.

**Comment by Presi5** [comment]
Thank you so much!

**Comment by Darkness-TX** [comment]
oh.......Which edition? Japanese or English(steam)?

**Comment by Presi5** [comment]
English, please.

**Comment by Darkness-TX** [comment]
Rioshiina ver2.50........BR is ver2.48.
It will take a while to analyze

**Comment by Presi5** [comment]
I understand, I really appreciate your help!

**Comment by Darkness-TX** [comment]
I'm not sure that the English version of this game is in two versions?
One of the filename is SJSE_xxxxx,another is SJSEZ_xxxxx ?
This two versions seem to use different encryption.    :(

**Comment by Darkness-TX** [comment]
OH,English version use shift-jis characters too.

**Comment by Darkness-TX** [comment]
update

**Comment by Presi5** [comment]
Thank you very much, that was fast. Just one more thing, but only if you have the time and the will: can you send me a prebuilt/builded version? I don't really know about c or c++  : /

**Comment by Darkness-TX** [comment]
[Sorcery Jokers.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/6563723/Sorcery.Jokers.zip)

**Comment by Presi5** [comment]
Thank you again, it works wonderfully. In case that I find some problems in the future, I'll reopen this issue and make you know.
