### ISSUE TITLE
Shiina Rio (Nukitashi support)

### ISSUE THREAD

**Issue by MishaIac** [Yggdrasill-Moe/Niflheim#23]
Hi. I want to ask you, is it possible to add Nukitashi (https://vndb.org/v22899) support for Shiina Rio tools?
I tried the latest version, which has Sorcery Joker support, but nothing works, although the engine version is the same (2500) and I know the keys. Maybe because I need Decode.bin and Extra.bin files and some kind of Seed? If so, unfortunately, I don't know what these files and Seed, and there are no instructions how to get them.

Here's what I know:
Version=2500
Key1=0x90B989AF
Key2=0x60BA6AB8
Key3=0x86B9E6B9
Key4=0xF3B999B9
Key5=0xF2B9BCA

RioShiinaImage, Region, EXE Nukitashi and sample WAR archives are in the zip archive:
[RioShiina_Nukitashi.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/7474458/RioShiina_Nukitashi.zip)

Thanks in advance.

**Comment by Darkness-TX** [comment]
[RioShiina_Nukitashi.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/7480929/RioShiina_Nukitashi.zip)

**Comment by Darkness-TX** [comment]
According to different games, the extra_encrypt, Seed and Extra.bin are also different.

**Comment by MishaIac** [comment]
Wow, its works! Thank you very much!
But the question still remains, how do I get extra_encrypt, Seed and Extra.bin? Or is there no easy way to explain it? I want to hack Nukitashi 2, too. Although, I haven't tested it yet, but could it be encrypted the same way as the first game?

**Comment by Darkness-TX** [comment]
Keys are also different.
I will introduce a method of finding this information by observation and reasoning, which I think can cope with most situations.
Decode.bin is not change in most cases. (I rarely deal with RioShiina engine, so I'm not sure).
RioShiina.jpg and RioShiina2.png can  be found in exe.But most of the time they are not change.
RioShiina_Extra.png is not used in all v2.50 games. Nukitashi isn't use.

So, most of the time we must find the change of Key, Extra.bin and extra_decrypt().

**Comment by Darkness-TX** [comment]
First of all, the simplest is to find the key.
Search the ending of RioShiina2.png in exe,the keys are behind RioShiina2.png.
So,the keys of Nukitashi 2 are:
Key1=0x96BF8FA9
Key2=0x66BC6CBE
Key3=0x80BFE0BF
Key4=0xF5BF9FBF
Key5=0x6CBFBAAE

<img width="1704" alt="QQ20211105-163828@2x" src="https://user-images.githubusercontent.com/22828117/140489256-27be10a3-5138-478d-80d3-16025bd2725a.png">

**Comment by Darkness-TX** [comment]
Next, the Extra.bin.
Extra.bin is a part of the exe, so each game is different.

1.Find the size of Extra.bin.
The game use RioShiina.jpg behind decrypt_helper4(), so we can search FileTimeToSystemTime().Then we can find the ImageSize of Image(line 612).
<img width="2183" alt="QQ20211105-164822@2x" src="https://user-images.githubusercontent.com/22828117/140490863-eda570c1-89c9-458f-9f1f-f3116f5b8f5b.png">
In Nukitashi 2,ImageSize is 0xBA31.
We know the size of RioShiina.jpg is 33484 bytes.
So the size of Extra.bin is 0xBA31 - 33484 = 0x3793.

2.Dump Extra.bin.
Search the ending of RioShiina.jpg in exe,the Extra.bin is behind RioShiina.jpg.
Start from 0xDEFE6,and dump 0x3793 bytes.
Yes,so easy.
<img width="1877" alt="QQ20211105-165013@2x" src="https://user-images.githubusercontent.com/22828117/140491399-e7c7dd17-3932-4960-bbaf-3872710c2782.png">

**Comment by Darkness-TX** [comment]
Next, analysis extra_decrypt(),the hardest step.
1.Find extra_decrypt().
Search 0x202 or 0xFF82AD82 in the debugger, extra_decrypt() is under push 202.
<img width="2047" alt="QQ20211105-171233@2x" src="https://user-images.githubusercontent.com/22828117/140492490-57f4aa98-d0f6-46cd-abce-90d87c9af366.png">

2.Analysis it!
You can dump the encrypted file like me.Then analyze it step by step.
<img width="2178" alt="QQ20211105-171515@2x" src="https://user-images.githubusercontent.com/22828117/140493136-c0886b48-ae93-4834-97bc-ebe9627d0f30.png">

**Comment by MishaIac** [comment]
I see. Maybe I can handle keys and Extra.bin, but I definitely can't handle extra_decrypt(), because, unfortunately, I don't know C and C++ very well, and assembler is even worse :(
I thought it would be easier...

**Comment by MishaIac** [comment]
Anyway, thanks for the instructions! Maybe when I learn more C and assembler, I'll manage it, but not now.
If you have already analyzed everything, is it possible to get tools for Nukitashi 2 too? I would be grateful.

**Comment by Darkness-TX** [comment]
A few hours for analysis, tired...
[NUKITASHI2.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/7488026/NUKITASHI2.zip)
.

**Comment by MishaIac** [comment]
Omg, thank you so much for your work! You are the best! 
The English version of Nukitashi should be out soon, and I hope they don't change the encryption, and if they do, I'll try to hack the game with your instructions. In any case, thanks and good luck :)

**Comment by MishaIac** [comment]
In the translation credits, we will be sure to mention you as the author of the tools. I hope you don't mind?

**Comment by Darkness-TX** [comment]
OK.I don't mind.

**Comment by MishaIac** [comment]
Ok. Thanks again.

**Comment by parasaite** [comment]
I have no experience with programs or code.
After all I do not understand. This problem will not be solved forever without the method of uploading the extracted data or adding the key or the garbro with the added key. It is very disappointing.

**Comment by MrShiruba** [comment]
Hello I'm sorry to reopen this issue but I've downloaded the provided link for "NUKITASHI2.zip" which seems to work on most of the files except for the main files named "NUKITASHI2_V1.WAR" and "NUKITASHI2_V2.WAR". Are they encrypted differently? Or maybe the tool should work with these and my files are different somehow?

Here is a link for the files that works(NUKITASHI2_S.WAR or NUKITASHI2.WAR) and that don't work (NUKITASHI2_V1.WAR and NUKITASHI2_V2.WAR).
https://drive.google.com/file/d/1oNm5Hs2S6674ok4szRvgQlUazw8pO34U/view?usp=sharing

**Comment by wycstc353** [comment]
> Hi. I want to ask you, is it possible to add Nukitashi (https://vndb.org/v22899) support for Shiina Rio tools? I tried the latest version, which has Sorcery Joker support, but nothing works, although the engine version is the same (2500) and I know the keys. Maybe because I need Decode.bin and Extra.bin files and some kind of Seed? If so, unfortunately, I don't know what these files and Seed, and there are no instructions how to get them.
> 
> Here's what I know: Version=2500 Key1=0x90B989AF Key2=0x60BA6AB8 Key3=0x86B9E6B9 Key4=0xF3B999B9 Key5=0xF2B9BCA
> 
> RioShiinaImage, Region, EXE Nukitashi and sample WAR archives are in the zip archive: [RioShiina_Nukitashi.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/7474458/RioShiina_Nukitashi.zip)
> 
> Thanks in advance.

大大，最近想研究这个引擎了，但是不是软件不同啊，我
![image](https://github.com/Yggdrasill-Moe/Niflheim/assets/39401653/1dbd1f49-130f-4f9b-a3d0-d8da4eb2603a)
试了一下这个exe，看了一下，十六进制和大大的图不同哎，我是准备先试下这种已经确定能改的，为啥不同呢
