### ISSUE TITLE
Problem with Ps3 scripts from CMVS engine. 

### ISSUE THREAD

**Issue by Berthog** [Yggdrasill-Moe/Niflheim#25]
Hello, I was testing the tools for cmvs engine in your repo and I got some problems with the ps3 dissambler, the dissambler didn't worked, in created this file but it is still encrypted. I tried to test it with hapymaher, amatsutsumi and aoitori, would you check it please? 
![image](https://user-images.githubusercontent.com/84604636/164756560-2d4605c4-f1f6-4071-8997-dbaa89d7a4ca.png)

**Comment by Berthog** [comment]
As side note, cpz unpacker worked well for all these games.

**Comment by Berthog** [comment]
Also, really sorry but could you explain how we can hook cmvs engine in order to load files from folder and not package for a tl project?

**Comment by Darkness-TX** [comment]
I hook cmvs engine use Yggdrasill-Moe/Longinus.
It's not very well to explain how to do it, but you can go to these addresses to see the assembly code, the assembly code of each game is similar
For Aoitori are:

[Longinus_Plus]
Plus_Engine=CMVS
CMVS_pGetFileName=0x45FFFF
CMVS_pGetDataSize=0x460089
CMVS_pCopyFileToMem=0x4600C8
CMVS_pCopyPicToMem=0x5160D9
