### ISSUE TITLE
S25 unpack request

### ISSUE THREAD

**Issue by seadog2099** [Yggdrasill-Moe/Niflheim#26]
直接编译的S25_unpack无法直接用在其他游戏上。我看过了关于WARC_unpack部分的issue，想问一下s25unpack是不是也要去找游戏特定的密钥和文件？需要找哪些部分？

另外再问一个问题，用Crass(Zeas)得到的s25文件是否和用该项目的WARC_unpack得到的文件不同？用前者得到的文件能用在s25unpack上吗？

Thanks in advance.

**Comment by Darkness-TX** [comment]
如果说你明确解包出了s25文件，并且这个s25文件是通过正确解密得到的，那应该是能用的，你可以上传一下文件，方便的话顺便说说是哪个游戏，s25unpack按理来说应该没问题，s25pack会有问题，如果你纯粹想解包，不如试试garbro。
按理来说crass对新版本的RioShiina是失效的，大概在2.48还是49开始失效，是老版本的引擎么，这个项目的WARC_unpack是针对特定游戏的，是Bloody Rondo。

**Comment by seadog2099** [comment]
Crass用的是Zeas版，按理说只能解2.49的包，不过解2.50的包还是成功得到了s25，解密是否正确就不知道了。
游戏是勇者を引退してよろず屋をオープンしたけど、なぜかアダルトグッズに人気が集中している件。呪われワーウルフ・ヘレナ。是2.5的引擎。
[EVA01D.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/8551483/EVA01D.zip)
得到的s25文件，用s25unpack会得到不支持的文件类型结果
https://pan.baidu.com/s/1Yf3mezxVRIeBVZXBxdMfTg?pwd=rrto
游戏源文件
garbro我也试了，用其他游戏的解密连s25文件都提不出来

**Comment by Darkness-TX** [comment]
2.50？那肯定不行的了，要重新分析解密，解出来的s25文件都是坏的

**Comment by seadog2099** [comment]
OK，了解了
