### ISSUE TITLE
Questions about Ivory

### ISSUE THREAD

**Issue by Cosetto** [Yggdrasill-Moe/Niflheim#27]
Hi there I have questions: Is there anything to repack it back to .pk format or hook it, write back to .SG format? And about the script, the Ivory I'm dealing with has .OCB, the python code works when I renamed it to .hk2, the question is there anything to insert the script back or the game can read from those .TEX without repacking?
![image](https://user-images.githubusercontent.com/81801486/165440015-da62525e-5929-478b-a89d-89300a78d2a8.png)

**Comment by DestinyFlame** [comment]
I wrote these Ivory‘s programs because of a translation project, but the translator didn't give me the translated text, so I didn't write the repack program.I don't know if anyone else has written repack program.

**Comment by Cosetto** [comment]
Well, the only tool for Ivory on github right now is yours and [this](https://github.com/morkt/GARbro/tree/master/ArcFormats/Ivory), but that only contains unpacker for .pk and converting of .SG to png
