### ISSUE TITLE
Guide for re-packing pac file

### ISSUE THREAD

**Issue by VijayKabbur** [Yggdrasill-Moe/Niflheim#28]
I'm trying to translate Koi Kakeru Shin Ai Kanojo(恋×シンアイ彼女). I used `fuckpac.exe -e data.pac` to extract _data.pac_ to a folder named _data_. But when I make a new _data.pac_ file using `fuckpac.exe -m data` and copy the new pac file to the game folder and run the game exe, it crashes with an error saying "ArchiveData Fail".

I get the same error even if I don't change anything in the data folder and repack it as is.
(When I did change something, I used _pac_text.py_ to extract _script.src_ and _text.dat_, changed the text from Japanese to English, and moved the new _script.src_ and _text.dat_ files to the _data_ folder.)

The options in fuckpac are:

- export: `exe -e pacfile`
- pack:   `exe -p oldpacfile`
- make:   `exe -m folder`
- dec:    `exe -de file`
- enc:    `exe -en file`

Can I get a brief description of all the options? I'm using only `-e` and `-m`. What are the other options for?
Do I need to use decrypt and encrypt options as well? 
When I use `fuckpac.exe -en data.pac`, a _data.pac.en_ file is created. What exactly is this file?

And what is the `-p` option? It created a _data.pac_new_ file. What is this file?

**Comment by VijayKabbur** [comment]
I figured out how to use `fuckpac.exe -m data` and `fuckpac.exe -p data.pac`. The problem was that it didn't work when I run those commands in _cmd.exe_, but they worked when I run the same commands in _PowerShell_. I wonder why it made a difference?

When running in _cmd_, Japanese and Chinese characters weren't printing properly either, but when running in _PowerShell_ using _Windows Terminal_, they were printing properly. Is it a problem with language codepages then?
![Screenshot 2022-04-28 210558](https://user-images.githubusercontent.com/53096977/165790685-996c1c97-1329-465d-9160-573d1b883ef7.png)

Anyway, the new pac file is working now. I can see the translated text in the game and the game doesn't crash.

I'd still like an explanation on the _decrypt_ `fuckpac.exe -de file.pac` and _encrypt_ `fuckpac.exe -en file.pac` options though. What do they actually do? How do I know when to use them?

**Comment by Darkness-TX** [comment]
If the first byte of data.dat file is $, fuckpac.exe will call the decryption/encryption function.

And, it's fuckpac.exe -de/-en data.dat, not for pac.

But, this engine can read files in folder mode.
You can export file from a abcd.pac, then make a folder which name is abcd in root folder, put one or more files in this folder which export from abcd.pac.
Note that if you need to read data.dat in folder mode, please encrypt first, use fuckpac.exe -en data.dat.
