### ISSUE TITLE
StudioSeldomAdventureSystem issue

### ISSUE THREAD

**Issue by xenei** [Yggdrasill-Moe/Niflheim#29]
I tried to extract text from CODE file, but I got this error **未能找到文本起始符**
I am guessing it is because every game have different structure CODE file>?
Do I need to edit something to extract? I'll attach the following CODE file, 
And the CODE file is from this small game - https://vndb.org/v30735
[CODE.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/8644162/CODE.zip)

Thank you.

**Comment by Darkness-TX** [comment]
This file cannot use SEC5_CODE_dump.py. It seems that there is no record length in the block. I'm afraid it needs to be greatly modified.

**Comment by Darkness-TX** [comment]
This file cannot use SEC5_CODE_dump.py. It seems that there is no record length in the block. I'm afraid it needs to be greatly modified.

**Comment by xenei** [comment]
I see, as I thought, it needs to be modified for other games, that's unfortunate since I don't think I can do it.
Thank you for your reply.
