### ISSUE TITLE
关于exhibit引擎的老版本的编码和边界

### ISSUE THREAD

**Issue by wedream3** [Yggdrasill-Moe/Niflheim#30]
第一次在在这里说话 如果提供信息不足 请告诉我

游戏空色的风琴 文本封在dll当中 游戏原exe有壳无法win7启动 
我在导入文本成功后 不知道这个引擎老版本怎样处理编码和边界 尽管我找到了脱壳的可以在win7运行的exe 
 想请问这个游戏的编码和边界如何搞定 
![MA~_1_5YDS6SZ92S  

> #4SR`AB](https://user-images.githubusercontent.com/106840368/171945712-83f6febc-d6b6-4c47-ab12-e4a7239214ad.png)

**Comment by Darkness-TX** [comment]
你就百度galgame边界检查或者编码修改就有相关文章了。
现在编码都是用hook处理了，你可以很多人都提交了自己写的hook工具，本仓库Longinus项目也算一个，然后一般都是hook CreateFontA或者CreateFontW或者CreateFontIndirectA或者CreateFontIndirectW，将字符编码的0x80改成0x86。
边界就具体问题具体分析了，一般搜索立即数0x80或0xa0，然后靠观察。

总的来说需要一下debugger的基础运用。

**Comment by wedream3** [comment]
我试过了才问的 编码我找不到80 边界看着也查过这个函数了

**Comment by wedream3** [comment]
我断过这个函数 但找不到80的位置 边界那边也找不到像的

**Comment by Darkness-TX** [comment]
你这是静态修改，这个就要自己找了，动态修改就是直接写个程序hook，模板一堆
