### ISSUE TITLE
大佬，能问下想解包封包RioShiina引擎的别的游戏的，需要修改你源码里的哪些参数啊，并且这些参数怎么找

### ISSUE THREAD

**Issue by wycstc353** [Yggdrasill-Moe/Niflheim#37]
大佬，能问下想解包封包RioShiina引擎的别的游戏的，需要修改你源码里的哪些参数啊，并且这些参数怎么找
[CHOSAIMIN_T.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/9733256/CHOSAIMIN_T.zip)
比如zhe'g这个超催眠術学園的CHOSAIMIN_T.WAR文件

**Comment by Darkness-TX** [comment]
https://github.com/Yggdrasill-Moe/Niflheim/issues/23
大概就是这样，不过如果garbro能解的话那就好办很多，不能解的话那就是新游戏，就需要按这issues中提到的方式去找

**Comment by wycstc353** [comment]
> #23 大概就是这样，不过如果garbro能解的话那就好办很多，不能解的话那就是新游戏，就需要按这issues中提到的方式去找

大佬，我这一共有两个椎名里绪2.5的游戏，ｏｎｏｍａｔｏｐｅ社的催眠ぱらだいす！garbro能解，能讲解下garbro能解的怎么处理吗，用你的原版吗？还是也有东西要改的，新游戏之后再研究
[催眠ぱらだいす！.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/9739201/default.zip)

**Comment by wycstc353** [comment]
对了，可以写成dll注入exe获取需要的参数和文件吗，
https://pan.baidu.com/s/1aDaKYD96wW0z9ezfvdUfOA
提取码：fo2c
这里面有个关于椎名里绪的解包就是dll注入的，我上面那个超催眠就可以用这个dll注入解包

**Comment by Darkness-TX** [comment]
vs打开garbro项目，可以直接在ArcWARC.cs文件的第170行下一个断点，直接运行调试，然后解war，然后随便双击个文件，如果garbro能解就会触发断点，vs左下角自动窗口那里就会显示这war包的信息，你这个催眠ぱらだいす！显示的是ExtraCrypt用的{GameRes.Formats.ShiinaRio.JokersCrypt}，HelperKey用的[0x0b2d7836, 0x3238cb38, 0xf838e438, 0x0000e338, 0x00000000]，ShiinaImage 的m_extra大小是0xade。

其实跟我贴的issue里说的方法一样，要改的地方你能照着找，我觉得我说得挺简单的了，就是garbro能解那一般情况下是省略了自己找extra_decrypt的步骤而已，这个是有难度的，其他感觉没啥难度，剩下的就是照着garbro写出extra_decrypt替换过去就完事了，JokersCrypt你可以看garbro的WarcEncryption.cs，直接文件中搜索JokersCrypt，我看这JokersCrypt类的加密还不是那么简单

**Comment by Darkness-TX** [comment]
你这dll我不会用

**Comment by wycstc353** [comment]
哎，算了，暂时放弃，看不懂，勉强能把key的看懂，之后改bin的都看不懂，garbro那个就更加困难了，希望之后有大佬能弄出来通用的解包exe吧，暂时放弃了，现在关于解包封包有加密的，感觉Siglus引擎的SiglusTools做得最好了，只要把游戏exe打开，这个就能读出key来，
dll是搜索一个dll注入软件，然后打开游戏exe，用这个软件把dll注入，然后会出来个黑弹窗，把要解包的拉到黑弹窗就能解包了，不过也不是通用的，我两游戏，就超催眠那个能解

http://www.downza.cn/soft/333742.html

**Comment by wycstc353** [comment]
> vs打开garbro项目，可以直接在ArcWARC.cs文件的第170行下一个断点，直接运行调试，然后解war，然后随便双击个文件，如果garbro能解就会触发断点，vs左下角自动窗口那里就会显示这war包的信息，你这个催眠ぱらだいす！显示的是ExtraCrypt用的{GameRes.Formats.ShiinaRio.JokersCrypt}，HelperKey用的[0x0b2d7836, 0x3238cb38, 0xf838e438, 0x0000e338, 0x00000000]，ShiinaImage 的m_extra大小是0xade。
> 
> 其实跟我贴的issue里说的方法一样，要改的地方你能照着找，我觉得我说得挺简单的了，就是garbro能解那一般情况下是省略了自己找extra_decrypt的步骤而已，这个是有难度的，其他感觉没啥难度，剩下的就是照着garbro写出extra_decrypt替换过去就完事了，JokersCrypt你可以看garbro的WarcEncryption.cs，直接文件中搜索JokersCrypt，我看这JokersCrypt类的加密还不是那么简单

大佬，2.49的话，是不是只要几个key就行了，还是和2.50一样，要弄出文件来的，突然发现超催眠只要不打游戏后来的补丁，它就是2.49的引擎
