### ISSUE TITLE
png2pgd在编译完成后如何使用

### ISSUE THREAD

**Issue by rentommy** [Yggdrasill-Moe/Niflheim#38]
![屏幕截图 2022-12-05 161526](https://user-images.githubusercontent.com/98695146/205587134-1d2f95c4-03de-45f1-bdc5-300c0526d77d.png)

**Comment by Darkness-TX** [comment]
需要libpng16.dll，然后拖pgd文件到程序图标上面就行。

看你问题的描述方式，感觉还需要多说几句？
无法在没有原pgd文件的基础上直接用png输出pgd，因为需要原pgd文件的一些信息，所以整个步骤就是先pgd2png.exe从pgd文件中导出png，然后修改png，然后png2pgd.exe生成新的pgd。

**Comment by rentommy** [comment]
用
![屏幕截图 2022-12-06 084107](https://user-images.githubusercontent.com/98695146/pgd2png.exe从pgd文件中导出png，然后修改png这些都可以做到，但是用png2pgd.exe生成新的pgd时提示

**Comment by rentommy** [comment]
用pgd2png.exe从pgd文件中导出png，然后修改png这些步骤都可以完成，但用png2pgd.exe生成新的pgd时提示
![屏幕截图 2022-12-06 084107](https://user-images.githubusercontent.com/98695146/205778221-6f29af76-da84-4b39-8336-a037fe3ffe63.png)
