### ISSUE TITLE
Error in pac_text.py

### ISSUE THREAD

**Issue by fushi002** [Yggdrasill-Moe/Niflheim#39]
First of all, thank you for making me a good tool.
A text extraction error occurred, so I'm asking you a question.

![image](https://user-images.githubusercontent.com/88200209/213362688-ba9ee96b-0a35-4c88-809c-06491b34dfaf.png)
The above error occurs.

This is the corresponding data file.

[data.pac](https://mega.nz/file/DkAARD6D#q4wLDr6ZxOWz-eoRREPFW_Xzls0bnqN4IV8R9rSx6xg)

I'd appreciate your help.

**Comment by Darkness-TX** [comment]
line 38
ofp.seek(0x4D670)

line 43
if i >= 0x9E:

line 84
if int(row[0]) >= 0x9E:

**Comment by fushi002** [comment]
Hello
I was greatly helped last time.
But there was another problem this time, so I'm leaving a message.
I want to translate another game, but the error occurs for the same reason as last time.
Can you take a look?

[data.pac](https://mega.nz/file/PlADBZrJ#Klw6TYkPQyAYqHltrlThz_-MhmPQOl6uLTweMdfolIM)

And if you have time, I'd like to learn how to find that address.
Because it would be rude to keep asking.
If it's hard to explain in detail, please tell me a trick.
Thank you!

**Comment by Darkness-TX** [comment]
https://github.com/Yggdrasill-Moe/Niflheim/issues/2
You can try it first.If you can't, I'll show you

**Comment by fushi002** [comment]
![image](https://user-images.githubusercontent.com/88200209/218926325-ca7ffab3-00a6-4a9a-b8c2-15e695d43444.png)

It was a great help!
Thanks to you, I was able to find it myself.
Thank you so much ❤️
