### ISSUE TITLE
提供一些引擎的资料和相关工具。希望对你有帮助。

### ISSUE THREAD

**Issue by a65090482** [Yggdrasill-Moe/Niflheim#4]
CMVS-Engine
来自：Xmoeproject
https://github.com/xmoeproject/CMVS-Engine

RioShiina 早期到中后期期版本密钥生成算法参考资料：
arc_conv
作者：w8m
https://github.com/amayra/arc_conv

RioShiina 近期版本密钥生成算法参考文件：
Rioshiina(ZeaS版)
链接：https://pan.baidu.com/s/1cRnvraryRvBzFtRb1P2ewA
Crass-final 源代码：
由痴漢公賊主写
https://github.com/rinrin-/crass/tree/c895a5ab425f68b91c2939288698df0df93d3ca1

ExtractGames
有对DDSystem做一些研究
来自：Alisa/Kerisa
https://github.com/Kerisa/ExtractGames

嗯，就这样了。

**Comment by a65090482** [comment]
希望对研究引擎、开发工具或由此构建的游戏有帮助，尤其是增强 Rioshiina 的泛用度。

**Comment by Darkness-TX** [comment]
你这么一说我想起来了，你就是那个Q名为飞翔的企鹅的对吧，我与你有过短暂的交流，而你给我留下了还算深的印象，很遗憾你这些东西我只看过xmoe的cmvs，其他的不需要看，DDSystem那个我甚至都写了解包器封包器，你知道你贴出来的Alisa大佬写的那个有什么功能吗？crass就更不用说了，不要把别人当傻子，因为对比起来说我觉得我们在这些方面比你更专业，你能想到的我们都能想到。
我无心去增强Rioshiina的泛用度，因为对于解包来说有更好的泛用工具，我们小组写的工具都是在基于有汉化坑的情况下，而现在2019年我们的安排是不再接新坑，所以Rioshiina的工具也仅仅停留在能完成BR的情况下。
况且，我已经告诉了你Rioshiina的特性，单靠一个解包器去搞泛用度，除非每次出新游戏都去找新游戏的密钥、某一步的特别解密方式、所使用到的解密图片，为何我会那么清楚需要找这三样东西而不是其他东西？这种纯粹就是苦力活，而我们对于解包galgame没有兴趣，我们只在有坑需要汉化的时候才会行动。
Rioshiina也就zeas写过的那个插件版本有点泛用的特性，毕竟是检索内存，可能还用到了inline hook，然而只要版本一更新或者主程序加了些反调试就大概率没有用了，他的思路是在开发解包器，我们的思路是在考虑怎么方便解包并在不使用内存注入的情况下封包成与原文件相同的格式，因为我们的动机是汉化。
cmvs这个引擎同理，写只需要原文件就能启动的解包器的话，每次新游戏出来都要找新的密钥。
请你相信，能出现在这个项目中的代码完成度上都算不错的，我们能搞出这些东西自然是花费了比你更多的时间，所以不如先提升下自己的水平，然后以写个泛用Rioshiina解包封包器为目标去做，看看会花费多少时间，等到时候再去看看上面说的我对Rioshiina的理解。
