### ISSUE TITLE
png2pgd tool does not function normally.

### ISSUE THREAD

**Issue by fushi002** [Yggdrasill-Moe/Niflheim#40]
Thank you for your help last time :)
I'm asking you a question because the image conversion tool is not working properly this time.
Below is the source file.
[file](https://mega.nz/file/OhxFmIaa#QKZXDHl6lE2HKQC3IDsq41BxxKtR83TGWHpAPOEBZIQ)

If you convert to png and then to pgd again, the image will not load normally.

Please check it out.
Thank you.

**Comment by Darkness-TX** [comment]
Usage:png2pgd.exe pgdfile
example:
png2pgd.exe TITLE_BASE01.PGD
Then TITLE_BASE01.PGDN will be created.
Because pgdfile's information is necessary.

**Comment by fushi002** [comment]
I don't think I explained enough.
I've learned how to use it.

Would you like to see this file first?
[file](https://mega.nz/file/zgwEgZJA#WlMMRKuFUTmd7YjptQmOHVWhORxCnuYV9k7lgyMR9iA)

We confirmed that there is no problem if the original title file (TITLE_BASE01.png) is converted as it is.
However, after modifying the png file (TITLE_BASE02.png), if you revert to the pgd file, an abnormal file will be created.

The image editor I used is Photoshop 2021.

I think it's a little unusual, but is it possible to solve it?

**Comment by Darkness-TX** [comment]
<img width="668" alt="t" src="https://user-images.githubusercontent.com/22828117/213948583-2c8465a5-f3d7-4772-86ca-335230bc2228.png">
The length, width and bpp must be the same as the original file.
So must be 32 bpp.
