### ISSUE TITLE
"勇者を引退してよろず屋を..." How do I extract?

### ISSUE THREAD

**Issue by mymzc4njm** [Yggdrasill-Moe/Niflheim#41]
Title: 勇者を引退してよろず屋をオープンしたけど、なぜかアダルトグッズに人気が集中している件
(https://vndb.org/r85615)
Developer: onomatope* raspberry
Engine: ShiinaRio(.WAR)

Hello. I need some help.
I want to extract from this game, but GARbro doesn't work anymore.
If anyone has any ideas, could you help me?

**Comment by Darkness-TX** [comment]
So troublesome, only help translation project.
