### ISSUE TITLE
Issue packing S25 files for Nukitashi

### ISSUE THREAD

**Issue by Alexeir-TL** [Yggdrasill-Moe/Niflheim#43]
HI Darkness! wonder if could help me with this:

Im trying to do a translation of Nukitashi in english and spanish and i was unpacking the WAR files for the system images and such, and found couple of S25 files that have a lot of the images that i want to translate. I can unpack them with the S25_unpack.exe you created.

But when packing the file again with S25_pack.exe i noticed that the file is considerably bigger than the original file: 

![image](https://user-images.githubusercontent.com/131127177/233500282-2a8c8a6d-929b-406c-979a-8dd73a1d7d57.png)

and when packing it back into the WAR file and trying to open the game, it is crashing with the following error:

![image](https://user-images.githubusercontent.com/131127177/232675528-330db19f-52ab-4c70-abb0-510e29b88cda.png)

Im not that good with programming so im not sure if i made a mistake when compiling the tools or something. Im attaching the S25 tools i used, and the S25 file that i wanted to unpack, translate and pack.

Can you check to see if you notice anything wrong or off, or if you have S25_pack.exe that works with the file im attaching?

[s25.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/11290830/s25.zip)

Again thanks for all you do for the community!

**Comment by Darkness-TX** [comment]
Yes, pack tool has a bug for some picture, and I usually only work on translation projects. Last time for RioShiina, I didn't need to deal with the pictures so didn't fix it. All right, I will take this opportunity to fix this bug.

**Comment by Darkness-TX** [comment]
Because of the fake compression of S25_decompress() is used in s25_pack, it is normal for the pack file to be larger than the original file.
But, during the WAR packing step, it will be recompressed.

**Comment by Cosetto** [comment]
> HI Darkness! wonder if could help me with this:
> 
> Im trying to do a translation of Nukitashi in english and spanish and i was unpacking the WAR files for the system images and such, and found a couple of S25 files that have a lot of the images that i want to translate. I can unpack them with the S25_unpack.exe you created.
> 
> But when packing the file again with S25_pack.exe i noticed that the file is considerably bigger than the original file:
> 
> ![image](https://user-images.githubusercontent.com/131127177/233500282-2a8c8a6d-929b-406c-979a-8dd73a1d7d57.png)
> 
> and when packing it back into the WAR file and trying to open the game, it is crashing with the following error:
> 
> ![image](https://user-images.githubusercontent.com/131127177/232675528-330db19f-52ab-4c70-abb0-510e29b88cda.png)
> 
> Im not that good with programming so im not sure if i made a mistake when compiling the tools or something. Im attaching the S25 tools i used, and the S25 file that i wanted to unpack, translate and pack.
> 
> Can you check to see if you notice anything wrong or off, or if you have S25_pack.exe that works with the file im attaching?
> 
> [s25.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/11290830/s25.zip)
> 
> Again thanks for all you do for the community!

https://twitter.com/shiravune/status/1651392668721876998?s=46&t=xZw71mZvKXNJD1nLkZHY_Q
