### ISSUE TITLE
.fnt (FNT4)

### ISSUE THREAD

**Issue by imKota** [Yggdrasill-Moe/Niflheim#44]
Hello!

Can you add support this font ?

https://github.com/DCNick3/shin/blob/master/shin-core/src/format/font.rs
https://github.com/andOlga/kaleido/tree/saku/fnt

![image](https://github.com/Yggdrasill-Moe/Niflheim/assets/24241471/f7c02ed2-f3d1-4f2d-866b-b192f3e67a84)

[font_00.fnt.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/12139840/font_00.fnt.zip)

**Comment by Darkness-TX** [comment]
Can't do it.
Never studied Rust and Ruby.

**Comment by imKota** [comment]
That's too bad, but thanks for the reply!
