### ISSUE TITLE
运行KaGuYa/arc_unpack.c时报错Segmentation fault

### ISSUE THREAD

**Issue by RoadToNowhereX** [Yggdrasill-Moe/Niflheim#46]
如图所示
<img width="678" alt="image" src="https://github.com/Yggdrasill-Moe/Niflheim/assets/37441177/0fe73918-c13b-4dbd-81fd-71ff48fdb9dc">

如果略过此处继续运行则会直接结束程序

**Comment by Darkness-TX** [comment]
这是命令行程序，编译了再运行，下面那段英文已经提示了你怎么做了，当然我本身写的是中文就是了……

**Comment by RoadToNowhereX** [comment]
> 这是命令行程序，编译了再运行，下面那段英文已经提示了你怎么做了，当然我本身写的是中文就是了……

编译的过程中已经报错了，

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffb576ef04a in strcpy () from C:\Windows\System32\msvcrt.dll

再用cmd运行编译好的exe也是程序直接结束。
那段英文是我自己改的，不知道为什么直接复制到vscode里面会跑出来乱码。

**Comment by RoadToNowhereX** [comment]
> 这是命令行程序，编译了再运行，下面那段英文已经提示了你怎么做了，当然我本身写的是中文就是了……

界面停在那里是因为vscode报错时自动帮我暂停了程序，实际上根本不能拖放文件

**Comment by Darkness-TX** [comment]
没用过vscode，既然出现了这段你改后的英文，那应该是编译成功了的。
我写的是“将arc文件拖到程序上”，具体点说应该是将arc文件拖到程序图标上，不是你先运行，然后再拖文件。
你要是想cmd来操作，那应该是这样：

arc_unpack.exe xxxx.arc

**Comment by Darkness-TX** [comment]
ReadIndex(argv[1]);
这里的argv[1]是指命令行的第一个参数，你要写arc文件的文件名（与exe在同一个目录下）或者arc文件的完整路径（与exe不在同一个目录下）

**Comment by RoadToNowhereX** [comment]
> 没用过vscode，既然出现了这段你改后的英文，那应该是编译成功了的。 我写的是“将arc文件拖到程序上”，具体点说应该是将arc文件拖到程序图标上，不是你先运行，然后再拖文件。 你要是想cmd来操作，那应该是这样：
> 
> arc_unpack.exe xxxx.arc

重新编译了下，直接把tblstr.arc和tblstr.ari拖过去，报错：文件头不是WFL1，游戏是[アトリエかぐや CheshireCat] 肉牝R30 ～肉欲に堕ちた牝たち～，应该也是kaguya引擎，不知道这个引擎是不是有不同的加密？

**Comment by Darkness-TX** [comment]
文本不是封包，arc_unpack是解包其他封包文件的，处理这引擎的时候当时文本不是我整的，我只处理了图片和封包，所以没有写文本处理相关的工具，记得文本只是异或了一下，没有其他加密，导出还是暴力导出的，反正有其他人处理完文本了那我也没去看，所以没像某些项目那样包含readme说明文件

**Comment by RoadToNowhereX** [comment]
> 文本不是封包，arc_unpack是解包其他封包文件的，处理这引擎的时候当时文本不是我整的，我只处理了图片和封包，所以没有写文本处理相关的工具，记得文本只是异或了一下，没有其他加密，导出还是暴力导出的，反正有其他人处理完文本了那我也没去看，所以没像某些项目那样包含readme说明文件

大佬有没有文本解包项目的指路？我在澄空看到说还和scr.arc这个文件有关，贼麻烦

**Comment by Darkness-TX** [comment]
没有
