### ISSUE TITLE
[cmvs | .cpz] Can't pack/unpack an archive

### ISSUE THREAD

**Issue by linakima** [Yggdrasill-Moe/Niflheim#47]
Game (english version): https://vndb.org/v10957

![cpz6](https://github.com/Yggdrasill-Moe/Niflheim/assets/34077156/fefd83d8-a3e6-49db-b7c8-85c0b16477a0)
![cpz7](https://github.com/Yggdrasill-Moe/Niflheim/assets/34077156/236972a0-a0ba-45c5-8141-48a7cd3b994b)

script.cpz: 
https://pixeldrain.com/u/yupg2RTL

**Comment by Cosetto** [comment]
https://github.com/morkt/GARbro
![image](https://github.com/Yggdrasill-Moe/Niflheim/assets/81801486/8aebf7fd-0d15-4dd0-b41d-9b7b12db17c0)

**Comment by Cosetto** [comment]
Completed in https://github.com/Dir-A/CMVS_Tools/issues/4

**Comment by Darkness-TX** [comment]
WTF!!!
It's cpz5.......not cpz6 or cpz7.
The game name is ?

**Comment by Cosetto** [comment]
He solved it, so there's no need to bother about that anymore
