### ISSUE TITLE
[cmvs | .cpz5] Can't pack the script archive

### ISSUE THREAD

**Issue by linakima** [Yggdrasill-Moe/Niflheim#48]
Hello it's me, [again](https://github.com/Yggdrasill-Moe/Niflheim/issues/47).
Game (english version): https://vndb.org/v10957
Direct link to game: https://pixeldrain.com/u/GSMQCaTq
Only script.cpz: https://pixeldrain.com/u/eQpnYn9B

Cosetto gave me the injector, it works fine on my side. But for some reason it doesn't work for some other players.
I was wondering if you could make a packer for the cpz5 archives?

**Comment by MishaIac** [comment]
Do not help this person under any circumstances, because he translates everything via DeepL from english to russian (https://vndb.org/p18672), and is not going to do a proper translation.

Сим, разлогинься, и иди отсюда нахер

**Comment by imKota** [comment]
Don't help him. He does machine translations even if someone translates normally, thus hindering normal translators. Who may still end up quitting translations.

Сим, не мешай нормальным переводчикам.
