### ISSUE TITLE
rld_text_output提取出错

### ISSUE THREAD

**Issue by komitanirin** [Yggdrasill-Moe/Niflheim#51]
bin文件确定是解密过的 两个密钥是
other_xor_key = 0x0E948C7A
def_xor_key = 0xAE85A916
游戏bin文本
[游戏原文本 解密.zip](https://github.com/user-attachments/files/15524968/default.zip)
但是运行 rld_text_output 时显示错误
Traceback (most recent call last):
    main()
  File "e:\GalgameTools\ExHIBIT\projects\星空TeaPartyえくすとら\加密解密\rld_text_output.py", line 106, in main
    dump_str = rld_output('defChara.bin')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\GalgameTools\ExHIBIT\projects\星空TeaPartyえくすとら\加密解密\rld_text_output.py", line 76, in rld_output
    row = dumpstr(src)
          ^^^^^^^^^^^^
  File "e:\GalgameTools\ExHIBIT\projects\星空TeaPartyえくすとら\加密解密\rld_text_output.py", line 25, in dumpstr
    return bstr.decode('932')
           ^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'cp932' codec can't decode byte 0xe7 in position 1130: illegal multibyte sequence
decoding with '932' codec failed
有时间的话能否麻烦你看一下
游戏链接：https://pan.baidu.com/s/1A_kOTmsTWV4hmkgZhD_W2Q?pwd=1234

**Comment by komitanirin** [comment]
成功的话，期末周过后我就开始汉化

**Comment by Darkness-TX** [comment]
defChara.rld这文件不知为啥有一段解密错误或者说没解密，好在那部分影响不大可以忽略。
懒得搞F2A好久没登录GitHub了，正好今年8月前都很忙所以issues也变成一个月看一次惹。

[rld.zip](https://github.com/user-attachments/files/15571615/rld.zip)

**Comment by komitanirin** [comment]
请问以后有时间的话方便写文本回封的程序吗 愿意的话我就接这个游戏的汉化了

**Comment by Darkness-TX** [comment]
行，这引擎的程序没写完回封也是因为当初发了文本后最终翻译没给回我翻译后的文本所以就搁置了。一直以来都是有人带着翻译完的文本过来，只要不是撞坑的我有时间的话都会帮忙，就是今年上半年有重要的事，积累了好几个坑还在排队等完成，要8月开始才有空了

**Comment by moemoee** [comment]
> 请问以后有时间的话方便写文本回封的程序吗 愿意的话我就接这个游戏的汉化了

试试这个https://github.com/regomne/chinesize/tree/master/ExHIBIT/extRld
