### ISSUE TITLE
tbl_chs.txt is missing

### ISSUE THREAD

**Issue by 0xh3LL0** [Yggdrasill-Moe/Niflheim#7]
looks like tbl_chs.txt which is needed for fuckfont is not included?

**Comment by Darkness-TX** [comment]
This thing deals with Chinese. First of all, tell me what you want to do with it.

**Comment by 0xh3LL0** [comment]
i want to edit the font and make it smaller, since there is no options for the font size within the game, i notice it just now that in order to pack the font, i need those file which is not present (though i said it worked earlier, my apologize)

so summary, i tried to unpack the font, edit them, make it smaller, then pack the font, thats it...

**Comment by Darkness-TX** [comment]
Some games have custom font,it is default_font.dat.
The feature is that there are three font options available 
Selecting the third font option in the settings will use default_font.dat.
The first and second font options are system fonts 
If it have a custom font, you may change default_font.dat to take effect.If not, you need other method.


fuckfont not used to modify font size,I recommend this method:
Unpack data. pac to get system. ini，put system.ini under the same directory as xxx.exe
edit system.ini:
DEF_FONT_TYPE = 4
to
DEF_FONT_TYPE = 0
(it meens use system fonts,0 meens use the first font options,1 meens use the second font options)
ADD_FONTNAME = "default_font"
to
;ADD_FONTNAME = "default_font"
(it meens disable custom fonts )
than edit FONT_SIZE option,save changes 
Finally, delete the save archive or delete save/system.dat,than start the game.
If you don't want to delete the save archive, you can modify save/system.dat.
The offset address of font size for each game may be different.
if FONT_SIZE = 28 in system.ini,
select 1c 00 00 00 in system.dat
If you choose the first font option,it will be 1c 00 00 00 00 00 00 00
If you choose the secont font option,it will be 1c 00 00 00 01 00 00 00
If you choose the third font option,it will be 1c 00 00 00 04 00 00 00
This change occurs when fonts are selected,This offset address may stores the font size.

**Comment by 0xh3LL0** [comment]
thank you very much, now i know how to change the size...

now,
i know that option for change font also available, but only limited to MS Gothic & MS Mincho which is rendered poorly, and i kinda dont like that.
is it there is any way to change the options for system font as well? something like change MS Gothic to SourceHans?
there is MS Gothic and MS Mincho on the extracted TEXT.DAT which is i tried to change to SourceHans, but it didnt take any effect.

**Comment by 0xh3LL0** [comment]
oh, forgot to mention, the default_font.dat from another game is just same, 
so i guess all sofpal games using the same font, perhaps...

**Comment by Darkness-TX** [comment]
![_20190301095302](https://user-images.githubusercontent.com/22828117/53610945-d22b4700-3c07-11e9-8671-ffa3767cc0f3.png)
change here

**Comment by 0xh3LL0** [comment]
nice, i'll try it later...

**Comment by 0xh3LL0** [comment]
okay, so i change the pal.dll from MS Mincho to SourceHans as follow
![error44](https://user-images.githubusercontent.com/23132217/53618884-d5323180-3c1f-11e9-8730-57a93f5da81a.png)
but it makes the game didnt launch, there is no error message or anything, the game simply didnt launch,
though i make sure the font name is correct
![error45](https://user-images.githubusercontent.com/23132217/53618946-14f91900-3c20-11e9-9cb6-eb3d26cbc27f.png)
font already installed on my system, but i copy the font file to the game directory as well

**Comment by Darkness-TX** [comment]
The first 源xxxxxxx seems to be longer than the MS明朝?
Try changing the font name is not that complicated and not so long

**Comment by 0xh3LL0** [comment]
nice, i edit the font name and make it shorter, it works now...
thank you!
