### ISSUE TITLE
sec5的问题

### ISSUE THREAD

**Issue by MZSHproject** [Yggdrasill-Moe/Niflheim#8]
sec5弄出来后是sec5几个区段命名的文件。  
那么问题来了……  
文本应该是在CODE段的，根据福音写的东西来看，要去主程序追一下解密，然后还要批量提取不同位置的文本人名选择支这些，那我怎么去知道文本人名选择支的位置？

**Comment by Darkness-TX** [comment]
sec5的文本我没去弄过，因为当时搞这引擎的时候文本别人弄了没需求，我去问问之前搞文本的大佬

**Comment by Darkness-TX** [comment]
他说他当时。。。。。。没关注这个问题，emmmm............

**Comment by MZSHproject** [comment]
那么他当时是怎么弄到文本的？直接hook文本吗？如果要hook的话大概需要注意什么？

**Comment by Darkness-TX** [comment]
https://tieba.baidu.com/p/4890032271
他照着这贴弄的

**Comment by MZSHproject** [comment]
好的，感谢大佬之路。

**Comment by a65090482** [comment]
https://github.com/Inori/FuckGalEngine
在这里有相对具体的代码，作者应该就是福音战士，不然那么多巧合怎么解释呢。

**Comment by MZSHproject** [comment]
事实上已经解决了，福音的代码我也看了。至于你说的巧合，我完全没理解到你说的啥。

**Comment by a65090482** [comment]
> 事实上已经解决了，福音的代码我也看了。至于你说的巧合，我完全没理解到你说的啥。

是哈，我是说Inori (Asuka) 竟然在研究Galgame时间上和引擎时间上奇迹般地吻合。这不禁让人联想到是同一个人啊。签名（或自述？）也对应福音战士01.

**Comment by MZSHproject** [comment]
> > 事实上已经解决了，福音的代码我也看了。至于你说的巧合，我完全没理解到你说的啥。
> 
> 是哈，我是说Inori (Asuka) 竟然在研究Galgame时间上和引擎时间上奇迹般地吻合。这不禁让人联想到是同一个人啊。签名（或自述？）也对应福音战士01.

是又如何？我没时间去研究Darkness-TX到底是不是福音，因为这对我毫无意义！
比起这些，我还是愿意看更多大佬的代码，拆更多的游戏来提升我自己的水平。毕竟在破解这一块我还只是个菜鸡。

**Comment by a65090482** [comment]
> 是又如何？我没时间去研究Darkness-TX到底是不是福音，因为这对我毫无意义！
> 比起这些，我还是愿意看更多大佬的代码，拆更多的游戏来提升我自己的水平。毕竟在破解这一块我还只是个菜鸡。

好吧，那再见了。另外我是说Inori一定是福音战士啦。以后再见。
