### ISSUE TITLE
SOFTPAL_ADV_SYSTEM help

### ISSUE THREAD

**Issue by imKota** [Yggdrasill-Moe/Niflheim#9]
Hello, @Darkness-TX !

Can you help me with offsets for **script.src** and **text.dat** from VN "Kizuna Kirameku Koi Iroha" ?
I try it:
![image](https://user-images.githubusercontent.com/24241471/60379926-d5fb9880-9a44-11e9-8f6c-a34859dd5173.png)

![image](https://user-images.githubusercontent.com/24241471/60379928-e01d9700-9a44-11e9-8e55-e72d647cfe2d.png)

```	src = open('TEXT.DAT', 'rb')
	dst = open('text.txt', 'w', encoding='utf16')
	ofp = open('SCRIPT.SRC','rb')
	dfp = open('script.txt','w',encoding='utf16')
	ofp.seek(0xd2cf0)
	src.seek(0x0C)
	count = byte2int(src.read(4))
	for i in range(0, count):
		if i >= 0x9a:
			off = src.tell()
			while 1:
				if byte2int(ofp.read(4)) == off:
					res = "○%08d○%X\n"%(i,ofp.tell() - 4)
					print('text num:%d script off:0x%X'%(i,ofp.tell() - 4))
					dfp.write(res)
					break
		num = byte2int(src.read(4))
		dst.write(FormatString(dumpstr(src),num))
	print('\nall %d row'%(count))
```
but..

![image](https://user-images.githubusercontent.com/24241471/60379937-25da5f80-9a45-11e9-9bf1-c68bb4884ac4.png)

[gamefiles.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/3341390/gamefiles.zip)

**Comment by Darkness-TX** [comment]
After NO.24, I think the offset may be trustworthy. 
[done.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/3341421/done.zip)

**Comment by imKota** [comment]
@Darkness-TX Thank you very much! You helped me a lot! )))
Sorry for my arrogance but.. I have another question for you. You do not know how to unpack and repack resources from these archives?
I have not been able to master them for a month. I learned everything that is written in the readme.txt, which is inside the archive.

It would be shifted translations from dead spots...

[fuckgalgame.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/3341447/fuckgalgame.zip)

**Comment by Darkness-TX** [comment]
STCM2L I I handled it in March, but the import was buggy so dump and import were not uploaded to github, i think dump is no problem. 
python STCM2L_dump.py folder

Other issues I haven't had time to deal with lately 
[STCM2L_dump.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/3342829/STCM2L_dump.zip)

**Comment by imKota** [comment]
@Darkness-TX thanks!
Maybe you have discord/veechat/whatsapp ?
If yes, can you write me on email aleksey-nyaka@yandex.ru ? I would like to discuss something personally.

**Comment by imKota** [comment]
@Darkness-TX 

> i think dump is no problem

It's problem:D
Because I could not unpack the texts т_т

**Comment by imKota** [comment]
@Darkness-TX about structure of an STCM file: [read this](https://github.com/u3shit/neptools/blob/358e8332fa33db17679ccabb3c2bf4eba2689f54/doc/formats/stcm.md)

**Comment by Darkness-TX** [comment]
？
![QQ截图20190630204138](https://user-images.githubusercontent.com/22828117/60396719-9e413d80-9b77-11e9-9fdb-086c94a57099.png)
![QQ截图20190630204205](https://user-images.githubusercontent.com/22828117/60396720-9e413d80-9b77-11e9-82e5-d456b22ebde4.png)

**Comment by imKota** [comment]
@Darkness-TX my fail..

**Comment by Darkness-TX** [comment]
I have finished import.
But import have problems with stuck in the selection,then the game cannot continue.
I don't have time to solve it.

**Comment by imKota** [comment]
> But import have problems with stuck in the selection,then the game cannot continue.

hmmm. Then there is the option of porting to renpy

**Comment by imKota** [comment]
@Darkness-TX What about the rest, can you say something (1,2,4)?

> [fuckgalgame.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/3341447/fuckgalgame.zip)

**Comment by imKota** [comment]
@Darkness-TX 
> I have finished import.
> But import have problems with stuck in the selection,then the game cannot continue.
> I don't have time to solve it.

Can you send me importer ? I try fix xD

**Comment by Darkness-TX** [comment]
[STCM2L.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/3343626/STCM2L.zip)
I write these two scripts based on the files I own. They can't handle what you own.

export:
python STCM2L_dump.py txt_bin
translation and put 100.txt into txt_cn
import:
python STCM2L_import.py txt_cn
new file will output into txt_out
tbl.txt is a modified Chinese coding table based on shift-jis(932)

**Comment by Darkness-TX** [comment]
Long time no see, recently I dealt with the game 十鬼の絆(psp)'s STCM2L program, found the bug in the previous program, so I took this opportunity to write a special version of the program to support the files you provided.
[STCM2L.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/3553678/STCM2L.zip)

**Comment by imKota** [comment]
@Darkness-TX Thanks for your help!

**Comment by imKota** [comment]
@Darkness-TX hello again :3
can you make fix for this files?
[txt_bin.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/3601506/txt_bin.zip)

**Comment by Darkness-TX** [comment]
[STCM2L.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/3603263/STCM2L.zip)

**Comment by imKota** [comment]
@Darkness-TX Oh thanks!
but 2_ichara.DAT dont unpack xD
[txt_bin.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/3603268/txt_bin.zip)

**Comment by Darkness-TX** [comment]
txt will not be generated without text to be translated.
If you modify text that does not require translation, you will get bugs.
if you want to dump all text,delete # in dump.py line 111 and 112 then add:
else:
	param_list.append(param)
	offset_dict[param] = src.tell() - 4
into import.py line 113.
if you want to add other opcode,see opcode_all.txt then add opcode into dump.py line 109 and import.py line 110.

**Comment by imKota** [comment]
Hello, @Darkness-TX!
Can you help me again? :D
[txt_bin.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/5683552/txt_bin.zip)

**Comment by Darkness-TX** [comment]
[txt_bin.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/5688589/txt_bin.zip)

**Comment by imKota** [comment]
@Darkness-TX 
> [txt_bin.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/5688589/txt_bin.zip)

Are there any options to extract all in chronological order?

For example:
voice
name
background
text

voice
name
background
text


I just want to port vn to another engine and I need chronological order of calls.

**Comment by Darkness-TX** [comment]
no........

**Comment by imKota** [comment]
@Darkness-TX hello! Again unpack problem:D
[SCRIPT.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/5762290/SCRIPT.zip)

**Comment by Darkness-TX** [comment]
[SCRIPT.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/5767805/SCRIPT.zip)
